// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/hongdagen/Go-000/Week_04/hyhy-demo-homework/internal/hyhy-demo/biz"
	"github.com/hongdagen/Go-000/Week_04/hyhy-demo-homework/internal/hyhy-demo/data"
	"github.com/hongdagen/Go-000/Week_04/hyhy-demo-homework/internal/hyhy-demo/service"
)

// Injectors from wire.go:

func InitOrderSave() *service.OrderSaveService {
	orderSaveRepository := data.NewOrderSaveRepository()
	orderSaveBIZ := biz.NewOrderSaveBIZ(orderSaveRepository)
	orderSaveService := service.NewOrderSaveService(orderSaveBIZ)
	return orderSaveService
}
